# fly.toml app configuration file generated for python-agent-example-floral-moon-7143 on 2024-11-03T17:52:31Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'python-agent-example-floral-moon-7143'
primary_region = 'iad'
kill_timeout = '5m0s'

[build]
  dockerfile = 'Dockerfile'
  ignorefile = '.dockerignore'

[deploy]
  strategy = 'bluegreen'

[env]
  PYTHONUNBUFFERED = '1'

[checks]
  [checks.healthcheck]
    port = 8081
    type = 'tcp'
    interval = '10s'
    timeout = '2s'
    grace_period = '5s'

[[vm]]
  memory = '4gb'
  cpu_kind = 'shared'
  cpus = 2
